name: 'Kivy App to APK'
description: 'Convert Kivy app to APK'
inputs:
  python-version:
    description: 'Python version to use'
    default: '3.8'
  work-dir:
    default: '.'
    description: 'Working directory'
  buildozer-cmd:
    default: 'echo y | buildozer -v android debug'
    description: 'Buildozer command to use'
branding:
  color: 'green'
  icon: 'play'
runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        architecture: x64
        python-version: ${{ inputs.python-version }}
    
    - name: Setup Java 17 required by Gradle
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Set JAVA_HOME
      run: |
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
      shell: bash
    
    - name: Install Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Prepare virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        echo "Using Python==$(python --version)"
      shell: bash
    
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git \
          zip \
          unzip \
          openjdk-17-jdk \
          python3-pip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          aidl \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev \
          wget
        export PATH=$PATH:~/.local/bin/
      shell: bash
    
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade \
          Cython==0.29.33 \
          buildozer
        if [ -f requirements.txt ]; then
          python3 -m pip install -r requirements.txt
        fi
      shell: bash
    
    - name: Install Android SDK components
      run: |
        yes | sdkmanager --licenses
        sdkmanager "build-tools;36.0.0"
        sdkmanager "platform-tools"
        sdkmanager "platforms;android-30"
        sdkmanager "ndk;25.1.8937393"
      shell: bash
    
    - name: Download Apache Ant
      run: |
        mkdir -p .buildozer/android/platform/apache-ant
        wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.10.12-bin.tar.gz -O ant.tar.gz
        tar -xzf ant.tar.gz -C .buildozer/android/platform/apache-ant --strip-components=1
      shell: bash
    
    - name: Build with Buildozer
      run: |
        echo y | buildozer -v android debug
      shell: bash
